package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type Field struct {
	Value string
}

type Struct struct {
	Name      string
	ShortName string
	Fields    []Field
}

type File struct {
	Package string
	Structs []Struct
}

const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset/main.go

package {{.Package}}

{{range .Structs}}
func ({{.ShortName}} *{{.Name}}) Reset() {
{{- range .Fields}}
{{.Value}}
{{- end}}
}
{{end}}
`

var tmpl = template.Must(template.New("header").Parse(templateStr))

func main() {
	fset := token.NewFileSet()

	packages := map[string]*File{}

	err := filepath.WalkDir(".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if path == "." {
			return nil
		}

		if d.IsDir() {
			name := d.Name()
			skippedDirNames := name == "vendor" || name == "testdata" || strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_")
			if skippedDirNames {
				return filepath.SkipDir
			}
		}

		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			fmt.Println("Ошибка парсинга файла: ", path)
			return nil
		}

		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}

			for _, s := range gd.Specs {
				ts := s.(*ast.TypeSpec)

				doc := ts.Doc
				if doc == nil && len(gd.Specs) == 1 {
					doc = gd.Doc
				}

				if !hasResetMarker(doc) {
					continue
				}

				var st *ast.StructType
				if st, ok = ts.Type.(*ast.StructType); !ok {
					continue
				}

				newStruct := createStruct(ts, st)

				dir := filepath.Dir(path)
				file, ok := packages[dir]
				if !ok {
					file = &File{Package: f.Name.Name}
					packages[dir] = file
				}

				file.Structs = append(file.Structs, newStruct)
			}
		}

		return nil
	})

	if err != nil {
		panic(err)
	}

	for dir, file := range packages {
		var buf bytes.Buffer
		err = tmpl.Execute(&buf, file)
		if err != nil {
			panic(err)
		}

		bufFmt, err := format.Source(buf.Bytes())
		if err != nil {
			fmt.Printf("=== %s: невалидный код ===\n%s\n", dir, buf.String())
			panic(err)
		}

		out := filepath.Join(dir, "reset.gen.go")
		err = os.WriteFile(out, bufFmt, 0644)
		if err != nil {
			panic(err)
		}
	}
}

func hasResetMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if text == "generate:reset" {
			return true
		}
	}
	return false
}

func createStruct(ts *ast.TypeSpec, st *ast.StructType) Struct {
	var str Struct

	str.Name = ts.Name.Name
	str.ShortName = "s"

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			if name := getEmbeddedName(field.Type); name != "" {
				str.Fields = append(str.Fields, createFieldValue(field, name, str.ShortName))
			}
			continue
		}
		for _, n := range field.Names {
			str.Fields = append(str.Fields, createFieldValue(field, n.Name, str.ShortName))
		}
	}

	return str
}

func createFieldValue(field *ast.Field, name, sn string) Field {
	var f Field
	var value string

	switch t := field.Type.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "complex64", "complex128", "uintptr", "byte", "rune":
			value = fmt.Sprintf("%s.%s = %v", sn, name, 0)
		case "string":
			value = fmt.Sprintf("%s.%s = %q", sn, name, "")
		case "bool":
			value = fmt.Sprintf("%s.%s = %v", sn, name, false)
		default:
			value = fmt.Sprintf("if r, ok := any(&%s.%s).(interface{ Reset() }); ok {\n\tr.Reset()\n}", sn, name)
		}
	case *ast.StarExpr:
		value = valueFromStarExpr(t, sn, name, 1)
	case *ast.ArrayType:
		value = fmt.Sprintf("%s.%s = %s.%s[:0]", sn, name, sn, name)
		if t.Len != nil {
			var arrLength string
			if bl, ok := t.Len.(*ast.BasicLit); ok {
				arrLength = bl.Value
			}
			switch elt := t.Elt.(type) {
			case *ast.Ident:
				value = fmt.Sprintf("%s.%s = [%s]%s{}", sn, name, arrLength, elt.Name)
			case *ast.StarExpr:
				if id, ok := elt.X.(*ast.Ident); ok {
					value = fmt.Sprintf("%s.%s = [%s]*%s{}", sn, name, arrLength, id.Name)
				}
			}
		}
	case *ast.MapType:
		value = fmt.Sprintf("clear(%s.%s)", sn, name)
	case *ast.SelectorExpr, *ast.StructType:
		value = fmt.Sprintf("if r, ok := any(&%s.%s).(interface{ Reset() }); ok {\n\tr.Reset()\n}", sn, name)
	case *ast.InterfaceType:
		value = fmt.Sprintf("if r, ok := %s.%s.(interface{ Reset() }); ok {\n\tr.Reset()\n}", sn, name)
	case *ast.FuncType, *ast.ChanType:
		value = fmt.Sprintf("%s.%s = nil", sn, name)
	}

	f.Value = value

	return f
}

func valueFromStarExpr(expr *ast.StarExpr, sn, n string, i int) string {
	var value string
	switch t := expr.X.(type) {
	case *ast.Ident:
		stars := strings.Repeat("*", i)
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "complex64", "complex128", "uintptr", "byte", "rune":
			value = fmt.Sprintf("if %s.%s != nil {\n\t%s%s.%s = %s\n}", sn, n, stars, sn, n, "0")
		case "string":
			value = fmt.Sprintf("if %s.%s != nil {\n\t%s%s.%s = %q\n}", sn, n, stars, sn, n, "")
		case "bool":
			value = fmt.Sprintf("if %s.%s != nil {\n\t%s%s.%s = %s\n}", sn, n, stars, sn, n, "false")
		default:
			value = fmt.Sprintf("if r, ok := any(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {\n\tr.Reset()\n}", sn, n, sn, n)
		}
	case *ast.SelectorExpr:
		value = fmt.Sprintf("if r, ok := any(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {\n\tr.Reset()\n}", sn, n, sn, n)
	case *ast.StarExpr:
		value = valueFromStarExpr(t, sn, n, i+1)
	}
	return value
}

func getEmbeddedName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.StarExpr:
		return getEmbeddedName(t.X)
	}
	return ""
}
