// Команда reset генерирует методы Reset() для структур, помеченных
// комментарием «// generate:reset».
//
// Утилита обходит все пакеты от текущей директории и ниже (пропуская vendor,
// testdata и директории, начинающиеся с «.» или «_»), находит помеченные
// структуры и для каждого пакета записывает файл reset.gen.go с методами
// Reset() для всех его помеченных структур. Запускать из корня модуля:
//
//	go run ./cmd/reset
//
// Reset() возвращает структуру к начальному состоянию по правилам:
//   - примитивы получают нулевое значение (0, "", false);
//   - слайсы обрезаются до нулевой длины с сохранением ёмкости (s[:0]);
//   - массивы заменяются нулевым массивом;
//   - мапы очищаются через clear;
//   - func и chan сбрасываются в nil;
//   - не-nil указатели на примитивы разыменовываются и сбрасываются;
//   - именованные типы (включая указатели на них и embedded-поля) вызывают
//     собственный Reset(), если он есть; наличие проверяется в рантайме через
//     type assertion, поэтому типы без Reset() остаются нетронутыми.
//
// Маркер учитывается как над отдельным объявлением type, так и над
// элементом группы type (...). Маркер над не-структурой игнорируется.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Field — один оператор сброса поля в теле Reset(), например «s.i = 0»
// или целый блок if для указателя.
type Field struct {
	Value string
}

// Struct описывает одну помеченную структуру для шаблона.
type Struct struct {
	Name      string  // имя типа
	ShortName string  // имя ресивера
	Fields    []Field // операторы сброса в порядке объявления полей
}

// File описывает содержимое одного reset.gen.go — все помеченные структуры
// одного пакета.
type File struct {
	Package string
	Structs []Struct
}

// templateStr — шаблон файла reset.gen.go. Первая строка соответствует
// соглашению «Code generated ... DO NOT EDIT.», по которому инструменты
// распознают сгенерированные файлы.
const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset/main.go

package {{.Package}}

{{range .Structs}}
func ({{.ShortName}} *{{.Name}}) Reset() {
{{- range .Fields}}
{{.Value}}
{{- end}}
}
{{end}}
`

var tmpl = template.Must(template.New("header").Parse(templateStr))

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "reset:", err)
		os.Exit(1)
	}
}

// run обходит текущую директорию, собирает структуры с маркером
// generate:reset и записывает reset.gen.go в каждый пакет, где они найдены.
func run() error {
	fset := token.NewFileSet()

	packages := map[string]*File{}

	err := filepath.WalkDir(".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if path == "." {
			return nil
		}

		if d.IsDir() {
			name := d.Name()
			skippedDirNames := name == "vendor" || name == "testdata" || strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_")
			if skippedDirNames {
				return filepath.SkipDir
			}
		}

		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			fmt.Println("Ошибка парсинга файла: ", path)
			return nil
		}

		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}

			for _, s := range gd.Specs {
				ts := s.(*ast.TypeSpec)

				doc := ts.Doc
				if doc == nil && len(gd.Specs) == 1 {
					doc = gd.Doc
				}

				if !hasResetMarker(doc) {
					continue
				}

				var st *ast.StructType
				if st, ok = ts.Type.(*ast.StructType); !ok {
					continue
				}

				newStruct := createStruct(ts, st)

				dir := filepath.Dir(path)
				file, ok := packages[dir]
				if !ok {
					file = &File{Package: f.Name.Name}
					packages[dir] = file
				}

				file.Structs = append(file.Structs, newStruct)
			}
		}

		return nil
	})

	if err != nil {
		return fmt.Errorf("обход директорий: %w", err)
	}

	for dir, file := range packages {
		var buf bytes.Buffer
		err = tmpl.Execute(&buf, file)
		if err != nil {
			return fmt.Errorf("%s: выполнение шаблона: %w", dir, err)
		}

		bufFmt, err := format.Source(buf.Bytes())
		if err != nil {
			fmt.Fprintf(os.Stderr, "=== %s: невалидный код ===\n%s\n", dir, buf.String())
			return fmt.Errorf("%s: форматирование сгенерированного кода: %w", dir, err)
		}

		out := filepath.Join(dir, "reset.gen.go")
		err = os.WriteFile(out, bufFmt, 0644)
		if err != nil {
			return fmt.Errorf("запись %s: %w", out, err)
		}
	}

	return nil
}

// hasResetMarker сообщает, содержит ли группа комментариев строку
// «generate:reset». Сравнение точное (после обрезки «//» и пробелов),
// чтобы не срабатывать на упоминания маркера в обычном тексте.
func hasResetMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if text == "generate:reset" {
			return true
		}
	}
	return false
}

// createStruct собирает описание структуры для шаблона: имя, ресивер и
// оператор сброса для каждого поля. Поле с несколькими именами (x, y int)
// даёт по оператору на имя; у embedded-поля имя берётся из его типа.
func createStruct(ts *ast.TypeSpec, st *ast.StructType) Struct {
	var str Struct

	str.Name = ts.Name.Name
	str.ShortName = "s"

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			if name := getEmbeddedName(field.Type); name != "" {
				str.Fields = append(str.Fields, createFieldValue(field, name, str.ShortName))
			}
			continue
		}
		for _, n := range field.Names {
			str.Fields = append(str.Fields, createFieldValue(field, n.Name, str.ShortName))
		}
	}

	return str
}

// createFieldValue строит оператор сброса для поля name структуры с
// ресивером sn, исходя из синтаксического вида типа поля. Тип, для которого
// правило не определено, даёт пустой оператор.
func createFieldValue(field *ast.Field, name, sn string) Field {
	var f Field
	var value string

	switch t := field.Type.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "complex64", "complex128", "uintptr", "byte", "rune":
			value = fmt.Sprintf("%s.%s = %v", sn, name, 0)
		case "string":
			value = fmt.Sprintf("%s.%s = %q", sn, name, "")
		case "bool":
			value = fmt.Sprintf("%s.%s = %v", sn, name, false)
		default:
			value = fmt.Sprintf("if r, ok := any(&%s.%s).(interface{ Reset() }); ok {\n\tr.Reset()\n}", sn, name)
		}
	case *ast.StarExpr:
		value = valueFromStarExpr(t, sn, name, 1)
	case *ast.ArrayType:
		value = fmt.Sprintf("%s.%s = %s.%s[:0]", sn, name, sn, name)
		if t.Len != nil {
			var arrLength string
			if bl, ok := t.Len.(*ast.BasicLit); ok {
				arrLength = bl.Value
			}
			switch elt := t.Elt.(type) {
			case *ast.Ident:
				value = fmt.Sprintf("%s.%s = [%s]%s{}", sn, name, arrLength, elt.Name)
			case *ast.StarExpr:
				if id, ok := elt.X.(*ast.Ident); ok {
					value = fmt.Sprintf("%s.%s = [%s]*%s{}", sn, name, arrLength, id.Name)
				}
			}
		}
	case *ast.MapType:
		value = fmt.Sprintf("clear(%s.%s)", sn, name)
	case *ast.SelectorExpr, *ast.StructType:
		value = fmt.Sprintf("if r, ok := any(&%s.%s).(interface{ Reset() }); ok {\n\tr.Reset()\n}", sn, name)
	case *ast.InterfaceType:
		value = fmt.Sprintf("if r, ok := %s.%s.(interface{ Reset() }); ok {\n\tr.Reset()\n}", sn, name)
	case *ast.FuncType, *ast.ChanType:
		value = fmt.Sprintf("%s.%s = nil", sn, name)
	}

	f.Value = value

	return f
}

// valueFromStarExpr строит оператор сброса для поля-указателя n. Указатель
// на примитив разыменовывается после проверки на nil; указатель на
// именованный тип вызывает его Reset() через type assertion. Параметр i —
// текущая глубина разыменования, растёт при рекурсии для **T.
func valueFromStarExpr(expr *ast.StarExpr, sn, n string, i int) string {
	var value string
	switch t := expr.X.(type) {
	case *ast.Ident:
		stars := strings.Repeat("*", i)
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "complex64", "complex128", "uintptr", "byte", "rune":
			value = fmt.Sprintf("if %s.%s != nil {\n\t%s%s.%s = %s\n}", sn, n, stars, sn, n, "0")
		case "string":
			value = fmt.Sprintf("if %s.%s != nil {\n\t%s%s.%s = %q\n}", sn, n, stars, sn, n, "")
		case "bool":
			value = fmt.Sprintf("if %s.%s != nil {\n\t%s%s.%s = %s\n}", sn, n, stars, sn, n, "false")
		default:
			value = fmt.Sprintf("if r, ok := any(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {\n\tr.Reset()\n}", sn, n, sn, n)
		}
	case *ast.SelectorExpr:
		value = fmt.Sprintf("if r, ok := any(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {\n\tr.Reset()\n}", sn, n, sn, n)
	case *ast.StarExpr:
		value = valueFromStarExpr(t, sn, n, i+1)
	}
	return value
}

// getEmbeddedName возвращает имя embedded-поля по его типу: для Nested и
// *Nested — «Nested», для pkg.T и *pkg.T — «T». Для остальных выражений
// возвращает пустую строку.
func getEmbeddedName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.StarExpr:
		return getEmbeddedName(t.X)
	}
	return ""
}
